title: Ebullient Emily
author: @epfeffer
email: emily.p.pfeffer@gmail.com
description: 
  Here's the description for my site...

# social links
linkedin_username: emilypfeffer # DO NOT include the @ character, or else the build will fail!
github_username:  epfeffer # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
