title: Ebullient Emily
author: @epfeffer
email: emily.p.pfeffer@gmail.com
description:
  Description TBD...

# social links
github_username:  epfeffer # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
